In [ ]:
  import tensorflow as tf

In [ ]:
tf.__version__

'2.9.2'

### Tensors Fundamental

In [ ]:
scalar=tf.constant(7) #creates tensor
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#number of dimension of a tensor
scalar.ndim

0

In [ ]:
vector = tf.constant([29,12])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([29, 12], dtype=int32)>

In [ ]:
#check vector dimension 
vector.ndim

1

In [ ]:
matrix= tf.constant([[10,7],
                     [7,10]])

In [ ]:
matrix.ndim

2

In [ ]:
a_matrix= tf.constant([[10.,7.],
                     [7.,10.],
                     [5,4]],dtype=tf.float16 )

In [ ]:
 a_matrix.ndim  #matrix has 2 dimensions

2

In [ ]:
yensor=tf.constant([[[10,7],
                     [7,10]],[[10,7],
                     [7,10]],[[10,7],
                     [7,10]]])

In [ ]:
yensor.ndim

3

In [ ]:
## Creating tensor using variable

In [ ]:
c_t=tf.Variable([10,7])
uc_t=tf.constant([10,7])

In [ ]:
c_t,uc_t

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
c_t[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# constant does allow changing tensor after declaration
# variable allow value to change but we can't change shape and dtype

In [ ]:
# Random tensor(use to intialize weights)

In [ ]:
random1= tf.random.Generator.from_seed(42)  #set seed
random1=random1.normal(shape=(4,2))
random1

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [ ]:
random2= tf.random.Generator.from_seed(7)  #set seed
random2=random2.uniform(shape=(4,2))
random2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.39932835, 0.7840713 ],
       [0.67880154, 0.73395896],
       [0.5520444 , 0.10948515],
       [0.6487982 , 0.9890779 ]], dtype=float32)>

In [ ]:
# setting seed are pseudo random number

In [ ]:
## shuffle order of element in tensor(when we have to shuffle data so order doesn't affect learning)

In [ ]:
tf.random.shuffle(random2,seed=7)
tf.random.set_seed(32)
random2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.39932835, 0.7840713 ],
       [0.67880154, 0.73395896],
       [0.5520444 , 0.10948515],
       [0.6487982 , 0.9890779 ]], dtype=float32)>

In [ ]:
new= tf.random.Generator.from_seed(5)
new=new.normal(shape=(5,3))
new

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 1.0278524 ,  0.27974114, -0.01347923],
       [ 1.845181  ,  0.97061104, -1.0242516 ],
       [-0.6544423 , -0.29738766, -1.3240396 ],
       [ 0.28785667, -0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707, -0.06378496]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
print(tf.random.shuffle(new))
print(tf.random.shuffle(new))

tf.Tensor(
[[ 0.69211644  0.84215707 -0.06378496]
 [-0.6544423  -0.29738766 -1.3240396 ]
 [ 1.845181    0.97061104 -1.0242516 ]
 [ 0.28785667 -0.8757901  -0.08857018]
 [ 1.0278524   0.27974114 -0.01347923]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[-0.6544423  -0.29738766 -1.3240396 ]
 [ 0.69211644  0.84215707 -0.06378496]
 [ 1.0278524   0.27974114 -0.01347923]
 [ 1.845181    0.97061104 -1.0242516 ]
 [ 0.28785667 -0.8757901  -0.08857018]], shape=(5, 3), dtype=float32)


In [ ]:
#if we want shuffle order to be reproducable we have set global as well as operational seed

In [ ]:
tf.ones([10,7]) # Create tensor of all ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# turn numpyy arra into tensors the main difference between numpy and tensor is that tensor can run on GPU at faster computing speed

In [ ]:
import numpy as np
a=np.arange(1,25,dtype=np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(a,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
b= np.arange(1,95,6)
b

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91])

In [ ]:
m=tf.constant(b,shape=(4,2,2))
m

<tf.Tensor: shape=(4, 2, 2), dtype=int64, numpy=
array([[[ 1,  7],
        [13, 19]],

       [[25, 31],
        [37, 43]],

       [[49, 55],
        [61, 67]],

       [[73, 79],
        [85, 91]]])>

In [ ]:
m.ndim

3

In [ ]:
## Information from tensors

In [ ]:
a=np.arange(6,132,step=4)

In [ ]:
len(a)

32

In [ ]:
fd=tf.constant(a,shape=(2,4,2,2))
fd

<tf.Tensor: shape=(2, 4, 2, 2), dtype=int64, numpy=
array([[[[  6,  10],
         [ 14,  18]],

        [[ 22,  26],
         [ 30,  34]],

        [[ 38,  42],
         [ 46,  50]],

        [[ 54,  58],
         [ 62,  66]]],


       [[[ 70,  74],
         [ 78,  82]],

        [[ 86,  90],
         [ 94,  98]],

        [[102, 106],
         [110, 114]],

        [[118, 122],
         [126, 130]]]])>

In [ ]:
fd[1][2]

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[102, 106],
       [110, 114]])>

In [ ]:
fd.shape,fd.ndim,tf.size(fd)

(TensorShape([2, 4, 2, 2]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=32>)

### Attributes of Tensor

In [ ]:
print("Datatype ",fd.dtype)
print("Dimension ",fd.ndim)
print("Shape",fd.shape)
print("element in first axis ",fd.shape[0])
print("element in last axis ",fd.shape[-1])
print("Total ele ",tf.size(fd))
print("Total ele ",tf.size(fd).numpy())


Datatype  <dtype: 'int64'>
Dimension  4
Shape (2, 4, 2, 2)
element in first axis  2
element in last axis  2
Total ele  tf.Tensor(32, shape=(), dtype=int32)
Total ele  32


In [ ]:
a=np.zeros([4,2,3,7])

In [ ]:
ten=tf.constant(a)

In [ ]:
ten.ndim

4

In [ ]:
tf.size(ten).numpy()

168

In [ ]:
ten.shape[-1]

7

In [ ]:
ten.shape[0]

4

In [ ]:
print("Datatype ",ten.dtype)
print("Dimension ",ten.ndim)
print("Shape",ten.shape)
print("element in first axis ",ten.shape[0])
print("element in last axis ",ten.shape[-1])
print("Total ele ",tf.size(ten))
print("Total ele ",tf.size(ten).numpy())

Datatype  <dtype: 'float64'>
Dimension  4
Shape (4, 2, 3, 7)
element in first axis  4
element in last axis  7
Total ele  tf.Tensor(168, shape=(), dtype=int32)
Total ele  168


In [ ]:
 ten[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float64, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])>

In [ ]:
#get first element from each dim except last
ten[:1,:,:1,:1]

<tf.Tensor: shape=(1, 2, 1, 1), dtype=float64, numpy=
array([[[[0.]],

        [[0.]]]])>

In [ ]:
ten

<tf.Tensor: shape=(4, 2, 3, 7), dtype=float64, numpy=
array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [ ]:
# Create rank2 
r2=np.arange(45,step=4)

In [ ]:
len(r2)

12

In [ ]:
rk2=tf.constant(r2,shape=(3,4))

In [ ]:
rk2[1][2].numpy()

24

In [ ]:
rk2

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])>

In [ ]:
rk2[:,-1]

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([12, 28, 44])>

In [ ]:
rk3=rk2[...,tf.newaxis]
rk3

<tf.Tensor: shape=(3, 4, 1), dtype=int64, numpy=
array([[[ 0],
        [ 4],
        [ 8],
        [12]],

       [[16],
        [20],
        [24],
        [28]],

       [[32],
        [36],
        [40],
        [44]]])>

In [ ]:
tf.expand_dims(rk2,axis=0).ndim

3

### Tensor Operation

In [ ]:
tensor=tf.constant([[10,17],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 27],
       [13, 14]], dtype=int32)>

In [ ]:
tensor #tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 17],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 170],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.multiply(tensor,10)    #tensorflow built in operation 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 170],
       [ 30,  40]], dtype=int32)>

In [ ]:
#tf built in funciton operate faster  on gpu

###Matrix Multiplication


In [ ]:
# ml matrix multiplicaition is very common operation

In [ ]:
tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[151, 238],
       [ 42,  67]], dtype=int32)>

In [ ]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 289],
       [  9,  16]], dtype=int32)>

In [ ]:
t1=tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t2=tf.constant([[3,5],[6,7],[1,8]])

In [ ]:
tf.linalg.matmul(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
t1@t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
X=tf.constant([[1,2,3,9]
               ,[5,9,4,6]])
Y=tf.constant([[1,12],[13,96],[24,6],
               [1,23],[3,6],[3,6]
               ,[4,2],[3,9],[2,6]])

In [ ]:
X=tf.reshape(X,(2,4))

In [ ]:
Y=tf.reshape(Y,(2,9))

In [ ]:
X

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 9],
       [5, 9, 4, 6]], dtype=int32)>

In [ ]:
tf.transpose(X)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 9],
       [3, 4],
       [9, 6]], dtype=int32)>

In [ ]:
tf.reshape(X,(2,4))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 9],
       [5, 9, 4, 6]], dtype=int32)>

##### In neural network a lot of transormation is done

In [ ]:
tf.transpose(X)@Y

<tf.Tensor: shape=(4, 9), dtype=int32, numpy=
array([[ 31,  27,  43, 116,  34,  21,  46,  33,  33],
       [ 56,  51,  80, 228,  66,  39,  83,  64,  60],
       [ 27,  48,  63, 304,  80,  30,  39,  77,  33],
       [ 45, 126, 153, 888, 228,  72,  63, 219,  63]], dtype=int32)>

#### Dot product is also called matrix multiplication


*   tf.matmul()
*   tf.tensordot()


In [ ]:
X,Y

(<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 9],
        [5, 9, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
 array([[ 1, 12, 13, 96, 24,  6,  1, 23,  3],
        [ 6,  3,  6,  4,  2,  3,  9,  2,  6]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(4, 9), dtype=int32, numpy=
array([[ 31,  27,  43, 116,  34,  21,  46,  33,  33],
       [ 56,  51,  80, 228,  66,  39,  83,  64,  60],
       [ 27,  48,  63, 304,  80,  30,  39,  77,  33],
       [ 45, 126, 153, 888, 228,  72,  63, 219,  63]], dtype=int32)>

In [ ]:
m=tf.constant([[13,24,53],
    [32,34,19]])
n=tf.constant([[34,25,5],
               [8,76,12]])

In [ ]:
m@tf.transpose(n)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1307, 2564],
       [2033, 3068]], dtype=int32)>

In [ ]:
tf.transpose(m)@n

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 698, 2757,  449],
       [1088, 3184,  528],
       [1954, 2769,  493]], dtype=int32)>

In [ ]:
tf.reshape(m,(3,2))@n

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 634, 2149,  353],
       [2058, 3757,  649],
       [1308, 2294,  398]], dtype=int32)>

In [ ]:
print('Normal Y ')
print(n)
print('Reshaped Y ')
print(tf.reshape(n,(3,2)))
print('Transpose Y ')
print(tf.transpose(n))

Normal Y 
tf.Tensor(
[[34 25  5]
 [ 8 76 12]], shape=(2, 3), dtype=int32)
Reshaped Y 
tf.Tensor(
[[34 25]
 [ 5  8]
 [76 12]], shape=(3, 2), dtype=int32)
Transpose Y 
tf.Tensor(
[[34  8]
 [25 76]
 [ 5 12]], shape=(3, 2), dtype=int32)


 Generally when performing multiplication on two tensor and axes doesn't line up we will more often use transpose

**Change Datatype**


> tf.cast


In [ ]:
#default dataype is float32 or int32
C=tf.constant([1.3,2.3])
C.dtype

tf.float32

In [ ]:
#default dataype is float32 or int32
d=tf.constant([1,2])
d.dtype

tf.int32

In [ ]:
# Modern accelarator can run model faster in 16 bit precision

In [ ]:
D=tf.cast(C,dtype=tf.float16)

In [ ]:
e=tf.cast(d,dtype=tf.float16)
e

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

Aggregating tensor


> Agrregation in tensor is condensing them from multiple values to smaller amount values




In [ ]:
# Get absolu value
D= tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of aggregation 

* get min
* get max
* get mean 
* get sum

In [ ]:
tn=tf.constant(np.arange(80,step=7),shape=(3,4))

In [ ]:
tn

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[ 0,  7, 14, 21],
       [28, 35, 42, 49],
       [56, 63, 70, 77]])>

In [ ]:
tf.reduce_min(tn,axis=1,keepdims=True)

<tf.Tensor: shape=(3, 1), dtype=int64, numpy=
array([[ 0],
       [28],
       [56]])>

In [ ]:
tf.reduce_max(tn,axis=0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([56, 63, 70, 77])>

In [ ]:
tf.reduce_mean(tn,axis=0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([28, 35, 42, 49])>

In [ ]:
tf.reduce_sum(tn,axis=0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 84, 105, 126, 147])>

In [ ]:
E=tf.constant(np.random.randint(0,100,size=50))

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2543>

In [ ]:
F=tf.reshape(E,shape=(5,10))

In [ ]:
E=tf.cast(E,dtype=tf.int32)

In [ ]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=675.7204>

In [ ]:
#Another way to find variance and std 
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=676>

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=25.994622520821494>

In [ ]:
# If we get type error go see documentation

positional max and min

1.   F[tf.argmax(F)]
2.   tf.reduce_max(F)



In [ ]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Return index of largest element across axis
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
 F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

**Squeezing a tensor**(Remove single dimension)

In [ ]:
tf.random.set_seed(30)
G= tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.5937799 , 0.05667603, 0.6462511 , 0.830739  , 0.06096888,
           0.4103918 , 0.9489596 , 0.33922124, 0.4374851 , 0.41155684,
           0.9732108 , 0.0500797 , 0.93884313, 0.39715505, 0.42824984,
           0.7619152 , 0.39822114, 0.5956578 , 0.8779398 , 0.10043168,
           0.21331716, 0.62426984, 0.06184375, 0.8005818 , 0.8525226 ,
           0.2827022 , 0.8048171 , 0.8986236 , 0.34012854, 0.7785393 ,
           0.08257508, 0.8811574 , 0.48566425, 0.04855621, 0.97528064,
           0.44055486, 0.9242524 , 0.49590588, 0.03022087, 0.4040637 ,
           0.28982878, 0.86573505, 0.48220754, 0.02629268, 0.41429532,
           0.20661616, 0.61409974, 0.78117085, 0.0346334 , 0.4491408 ]]]]],
      dtype=float32)>

In [ ]:
G_squeeze=tf.squeeze(G)
G_squeeze,G_squeeze.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.5937799 , 0.05667603, 0.6462511 , 0.830739  , 0.06096888,
        0.4103918 , 0.9489596 , 0.33922124, 0.4374851 , 0.41155684,
        0.9732108 , 0.0500797 , 0.93884313, 0.39715505, 0.42824984,
        0.7619152 , 0.39822114, 0.5956578 , 0.8779398 , 0.10043168,
        0.21331716, 0.62426984, 0.06184375, 0.8005818 , 0.8525226 ,
        0.2827022 , 0.8048171 , 0.8986236 , 0.34012854, 0.7785393 ,
        0.08257508, 0.8811574 , 0.48566425, 0.04855621, 0.97528064,
        0.44055486, 0.9242524 , 0.49590588, 0.03022087, 0.4040637 ,
        0.28982878, 0.86573505, 0.48220754, 0.02629268, 0.41429532,
        0.20661616, 0.61409974, 0.78117085, 0.0346334 , 0.4491408 ],
       dtype=float32)>, TensorShape([50]))

### [**One-Hot Encoding**]


> Form of numerical encoding

In [ ]:
sl=[0,1,2,3] # could be red,green,blue,purple

tf.one_hot(sl,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom value for one_hot
tf.one_hot(sl,depth=4,on_value="love dl ",off_value="hate ml")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'love dl ', b'hate ml', b'hate ml', b'hate ml'],
       [b'hate ml', b'love dl ', b'hate ml', b'hate ml'],
       [b'hate ml', b'hate ml', b'love dl ', b'hate ml'],
       [b'hate ml', b'hate ml', b'hate ml', b'love dl ']], dtype=object)>

In [ ]:
colour=[1,2,4,3]
tf.one_hot(colour,depth=5 ,on_value='fu',off_value='not_today')

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'not_today', b'fu', b'not_today', b'not_today', b'not_today'],
       [b'not_today', b'not_today', b'fu', b'not_today', b'not_today'],
       [b'not_today', b'not_today', b'not_today', b'not_today', b'fu'],
       [b'not_today', b'not_today', b'not_today', b'fu', b'not_today']],
      dtype=object)>

In [ ]:
colour=tf.constant(colour)
colour

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 4, 3], dtype=int32)>

In [ ]:
tf.one_hot(colour,depth=5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

Practice maths
Square,log,square_root

In [ ]:
H=tf.cast(tf.range(1,10),dtype='float16')
H

<tf.Tensor: shape=(9,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float16)>

In [ ]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [ ]:
H=tf.range(1,15)
tf.cast(H,tf.half)

<tf.Tensor: shape=(14,), dtype=float16, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.], dtype=float16)>

In [ ]:
tf.math.is_nan(tf.cast(H,tf.half))

<tf.Tensor: shape=(14,), dtype=bool, numpy=
array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])>

### Tensors and numpy

TensorFlow interacts beautifully with Numpy

In [ ]:
J=tf.constant(np.array([1.,3,4.]))

In [ ]:
np.array(J),type(np.array(J))

(array([1., 3., 4.]), numpy.ndarray)

In [ ]:
J.numpy(),type(J.numpy())

(array([1., 3., 4.]), numpy.ndarray)

In [ ]:
J.numpy()[0]

1.0

In [ ]:
# Default tyoe of each are slightly diffeent
numpy_j=tf.constant(np.array([3.,6.,.3]))
tensor_j=tf.constant([3.,6.,.3])
numpy_j.dtype,tensor_j.dtype

(tf.float64, tf.float32)

In [ ]:
vr=tf.constant([2,3,4,2])
vr,vr.ndim,vr.shape,tf.rank(vr).numpy()

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 2], dtype=int32)>,
 1,
 TensorShape([4]),
 1)

In [ ]:
sr=tf.constant(3)
sr,sr.ndim,sr.shape,tf.rank(sr).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=3>, 0, TensorShape([]), 0)

In [ ]:
mx=tf.constant([[1,4,6,3],
               [4,8,2,9],
               [3,86,23,55]])
mx,mx.shape,tf.rank(mx).numpy(),tf.size(mx).numpy()

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 1,  4,  6,  3],
        [ 4,  8,  2,  9],
        [ 3, 86, 23, 55]], dtype=int32)>, TensorShape([3, 4]), 2, 12)

In [ ]:
tf.random.set_seed(32)
a=tf.random.uniform(shape=(5,300))
b=tf.random.uniform(shape=(5,300))
print(a)
print(b)

tf.Tensor(
[[0.54520595 0.13372338 0.45232666 ... 0.45167708 0.8256048  0.9252931 ]
 [0.7212399  0.6417098  0.1694361  ... 0.40947497 0.52742505 0.6555792 ]
 [0.22098267 0.41154444 0.5549755  ... 0.95074594 0.4237417  0.01903772]
 [0.9836285  0.69332993 0.81684124 ... 0.5581968  0.36444438 0.19124126]
 [0.16698074 0.7840066  0.29173386 ... 0.88283336 0.35702634 0.76522374]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.20274532 0.0362395  0.45186257 ... 0.69017184 0.01630318 0.5514674 ]
 [0.9618223  0.75508356 0.25777328 ... 0.22629893 0.40577734 0.00108409]
 [0.7881732  0.9828061  0.01896739 ... 0.3543836  0.15920365 0.76062274]
 [0.14122677 0.21683455 0.7634512  ... 0.9755899  0.3852471  0.06009662]
 [0.05427301 0.01137054 0.31931353 ... 0.5983254  0.02609873 0.6930649 ]], shape=(5, 300), dtype=float32)


In [ ]:
# 4.
tf.matmul(a,tf.reshape(b,(300,5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.64762 , 73.56679 , 75.77454 , 75.62358 , 75.80945 ],
       [76.67738 , 73.55655 , 72.740234, 72.56367 , 75.00712 ],
       [76.37172 , 75.43523 , 77.82565 , 76.52347 , 77.844765],
       [73.14754 , 72.31564 , 72.21898 , 70.1387  , 70.89406 ],
       [77.3753  , 75.660904, 73.66423 , 77.18773 , 78.14657 ]],
      dtype=float32)>

In [ ]:
# 5.
tf.tensordot(tf.reshape(a,(300,5)),b,1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.66989064, 0.6100071 , 0.7155847 , ..., 1.2945164 , 0.22030252,
        1.3210255 ],
       [1.4130359 , 1.4019376 , 1.0572022 , ..., 1.8022512 , 0.5555213 ,
        1.5222584 ],
       [1.0558859 , 0.96709806, 0.9291327 , ..., 1.1413665 , 0.7202397 ,
        0.16103193],
       ...,
       [0.833067  , 0.8526717 , 0.44352165, ..., 0.8074335 , 0.3200858 ,
        0.7854406 ],
       [0.34011096, 0.27500167, 0.34948114, ..., 0.605096  , 0.13705574,
        0.6268087 ],
       [1.0458835 , 1.0793886 , 0.85187167, ..., 1.5822356 , 0.36358443,
        1.5689299 ]], dtype=float32)>

In [ ]:
# 6.
tf.random.set_seed(29)
t=tf.random.uniform(shape=(224,224,3),seed=5)

In [ ]:
tf.reduce_max(t,axis=1)
tf.reduce_min(t,axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[7.34126568e-03, 7.12645054e-03, 5.43951988e-03],
       [9.83715057e-04, 8.81910324e-04, 4.23336029e-03],
       [2.99930573e-03, 7.30061531e-03, 6.38508797e-03],
       [1.36721134e-03, 6.48856163e-03, 1.54560804e-02],
       [2.52830982e-03, 3.49068642e-03, 1.35600567e-03],
       [5.91516495e-04, 2.31623650e-04, 2.51448154e-03],
       [3.91173363e-03, 4.05120850e-03, 3.62300873e-03],
       [1.48923397e-02, 6.82091713e-03, 1.09752417e-02],
       [1.26934052e-03, 8.86142254e-03, 8.98122787e-04],
       [1.41382217e-04, 4.05025482e-03, 4.01151180e-03],
       [8.10623169e-05, 7.33733177e-04, 1.04894638e-02],
       [8.43644142e-03, 6.22105598e-03, 1.08802319e-03],
       [4.60112095e-03, 3.47459316e-03, 9.73224640e-04],
       [8.30066204e-03, 1.56176090e-02, 3.18455696e-03],
       [3.63659859e-03, 1.11269951e-03, 2.26736069e-03],
       [2.20239162e-03, 4.22716141e-03, 6.57427311e-03],
       [2.18641758e-03, 7.90119171e-04

In [ ]:
# 8.
tf.random.set_seed(29)
k=tf.random.uniform(maxval=5,shape=(1,224,224,3),seed=5)

In [ ]:
tf.squeeze(k)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[1.4021009 , 1.8675518 , 1.5603298 ],
        [0.09304941, 2.3895252 , 3.9792376 ],
        [1.4920115 , 4.8368244 , 4.783265  ],
        ...,
        [3.8914852 , 4.2835016 , 0.18297315],
        [0.29164493, 2.1747541 , 4.42418   ],
        [2.644087  , 3.4301102 , 1.6405797 ]],

       [[2.2442217 , 3.3641057 , 3.6955488 ],
        [4.2341833 , 4.0697374 , 1.2494171 ],
        [4.074918  , 0.65579116, 2.2132015 ],
        ...,
        [1.6810381 , 4.8352575 , 1.0307878 ],
        [4.089391  , 0.74312925, 3.877151  ],
        [1.5994054 , 1.5617597 , 3.538745  ]],

       [[0.87142944, 3.9099956 , 4.300552  ],
        [0.9679508 , 0.6646091 , 1.994552  ],
        [0.58356464, 3.5265775 , 1.5822071 ],
        ...,
        [0.8082652 , 0.03650308, 4.3051105 ],
        [0.01499653, 2.9171033 , 0.06836355],
        [2.925424  , 3.2992463 , 2.007956  ]],

       ...,

       [[1.1992943 , 0.16962767, 0.01576006],
        [1.13

In [ ]:
m=tf.random.uniform(maxval=10,shape=[10],dtype=tf.int32)
m

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 2, 7, 1, 6, 9, 0, 6, 7, 7], dtype=int32)>

In [ ]:
m[tf.argmax(m)]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
tf.one_hot(m,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>

In [ ]:
tf.constant(m,shape=(2,5))

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 2, 7, 1, 6],
       [9, 0, 6, 7, 7]], dtype=int32)>

In [ ]:
lg=tf.random.uniform(minval=2,maxval=50,shape=(4,5),dtype=tf.float32)
lg

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[27.800293,  5.90576 , 36.361595,  9.458206, 28.51223 ],
       [24.542377, 37.44001 , 11.845106, 15.251904, 15.23428 ],
       [20.733606, 21.383923, 34.907066, 38.752346, 38.925186],
       [43.934692, 12.453445, 41.465004, 40.94112 , 40.482018]],
      dtype=float32)>

In [ ]:
lg=tf.math.log(lg)
lg

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[3.3250465, 1.7759281, 3.5935133, 2.2468827, 3.3503332],
       [3.2004013, 3.62274  , 2.4719148, 2.7247043, 2.7235482],
       [3.031756 , 3.0626392, 3.5526893, 3.6571913, 3.6616416],
       [3.7827044, 2.5219972, 3.7248497, 3.7121348, 3.7008579]],
      dtype=float32)>

In [ ]:
lg=tf.math.exp(lg)
lg

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[27.800293 ,  5.90576  , 36.3616   ,  9.458205 , 28.512232 ],
       [24.542377 , 37.440014 , 11.845106 , 15.251903 , 15.234281 ],
       [20.733606 , 21.38392  , 34.907066 , 38.752346 , 38.92519  ],
       [43.934696 , 12.4534445, 41.465    , 40.941116 , 40.482018 ]],
      dtype=float32)>

In [ ]:
tf.reduce_mean(lg,axis=0)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([29.252743, 19.295784, 31.144691, 26.100893, 30.788431],
      dtype=float32)>

## Tensorflow Beginners function
Load data

Built NN

Train NN

Evaluate Accuracy

In [ ]:
mnist=tf.keras.datasets.mnist
(X_train,y_train),(X_test,y_test)=mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [ ]:
# Scaling neural network
X_train,X_test=X_train/255.0,X_test/255.0

In [ ]:
# Creating neuaral network

model=tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
# Choose loss funciton 
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
# Choose optimizer
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2981 - accuracy: 0.9126
Epoch 2/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1468 - accuracy: 0.9567
Epoch 3/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1105 - accuracy: 0.9663
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0905 - accuracy: 0.9724
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0789 - accuracy: 0.9754
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0673 - accuracy: 0.9788
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0612 - accuracy: 0.9807
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0535 - accuracy: 0.9832
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0497 - accuracy: 0.9834
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.046

In [ ]:
model.evaluate(X_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0709 - accuracy: 0.9790 - 601ms/epoch - 2ms/step


[0.07088503241539001, 0.9789999723434448]

In [ ]:
#Gives us probability of belonging to each category
probabilty_model=tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [ ]:
# Gives us what category do image belong to
tf.argmax(probabilty_model(X_test[:10]),axis=1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9])>

In [ ]:
y_test[:10]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9], dtype=uint8)